KEYWORDS = [
    "education",
    "training",
    "formation",
    "university",
    "e-learning",
    "digital learning",
    "skills",
    "curriculum",
    "higher education",
    "higher education",
    "tvet",
    "capacity building",
    "teaching",
    "pedagogy",
    "learning",
    "school",
    "student",
    "teacher",
    "academic",
    "research",
]

AFRICA_COUNTRIES = {
    "senegal": "Sénégal",
    "cote d'ivoire": "Côte d'Ivoire",
    "ivory coast": "Côte d'Ivoire",
    "morocco": "Maroc",
    "maroc": "Maroc",
    "tunisia": "Tunisie",
    "tunisie": "Tunisie",
    "cameroon": "Cameroun",
    "cameroun": "Cameroun",
    "mali": "Mali",
    "burkina": "Burkina Faso",
    "burkina faso": "Burkina Faso",
    "benin": "Bénin",
    "togo": "Togo",
    "niger": "Niger",
    "guinea": "Guinée",
    "guinee": "Guinée",
    "chad": "Tchad",
    "congo": "Congo",
    "drc": "RDC",
    "rd congo": "RDC",
    "gabon": "Gabon",
    "madagascar": "Madagascar",
    "algeria": "Algérie",
    "egypt": "Égypte",
    "ethiopia": "Éthiopie",
    "kenya": "Kenya",
    "nigeria": "Nigeria",
    "ghana": "Ghana",
    "south africa": "Afrique du Sud",
}

SCORING = {
    "education": 5,
    "training": 3,
    "university": 5,
    "higher education": 5,
    "tvet": 5,
    "digital": 2,
    "e-learning": 4,
    "skills": 3,
    "curriculum": 4,
    "capacity": 3,
    "teaching": 3,
    "pedagogy": 4,
    "academic": 3,
}

SOURCES = {
    "world_bank": {
        "name": "World Bank",
        "url": "https://projects.worldbank.org/en/projects-operations/projects-list",
        "priority": 1,
    },
    "bad": {
        "name": "BAD (African Development Bank)",
        "url": "https://www.afdb.org/en/projects-operations",
        "priority": 1,
    },
    "afd": {
        "name": "AFD",
        "url": "https://www.afd.fr/en/page-offres",
        "priority": 1,
    },
    "eu_ted": {
        "name": "EU TED",
        "url": "https://ted.europa.eu/en/search",
        "priority": 1,
    },
    "armp_senegal": {
        "name": "ARMP Senegal",
        "url": "https://www.marchespublics.sn",
        "priority": 2,
    },
    "portal_maroc": {
        "name": "Marches Publics Maroc",
        "url": "https://www.marchespublics.gov.ma",
        "priority": 2,
    },
    "tendersinfo": {
        "name": "TendersInfo",
        "url": "https://www.tendersinfo.com/global-Africa-tenders.php",
        "priority": 2,
    },
    "tendersontime": {
        "name": "TendersOnTime",
        "url": "https://www.tendersontime.com/northern-africa-tenders/",
        "priority": 2,
    },
    "globaltenders": {
        "name": "GlobalTenders",
        "url": "https://www.globaltenders.com",
        "priority": 2,
    },
    "tuneps": {
        "name": "TUNEPS Tunisia",
        "url": "https://www.tuneps.tn",
        "priority": 3,
    },
    "sigmap_civ": {
        "name": "SIGMAP Côte d'Ivoire",
        "url": "https://www.sigmap.org",
        "priority": 3,
    },
    "armp_cameroon": {
        "name": "ARMP Cameroon",
        "url": "https://www.armp.cm",
        "priority": 3,
    },
    "ministere_maroc": {
        "name": "Ministère Education Maroc",
        "url": "https://www.men.gov.ma",
        "priority": 3,
    },
    "ministere_tunisie": {
        "name": "Ministère Education Tunisie",
        "url": "https://www.education.gov.tn",
        "priority": 3,
    },
    "menetfp_civ": {
        "name": "MENETFP Côte d'Ivoire",
        "url": "https://www.menetfp.ci",
        "priority": 3,
    },
    "minesup_cameroon": {
        "name": "MINESUP Cameroon",
        "url": "https://www.minesup.gov.cm",
        "priority": 3,
    },
    "boad": {
        "name": "BOAD (West Africa)",
        "url": "https://www.boad.org",
        "priority": 4,
    },
    "bdeac": {
        "name": "BDEAC (Central Africa)",
        "url": "https://www.bdeac.int",
        "priority": 4,
    },
    "reliefweb": {
        "name": "ReliefWeb",
        "url": "https://reliefweb.int/updates?filter%5B%5D=type%3Ajob",
        "priority": 4,
    },
    "devex": {
        "name": "Devex",
        "url": "https://www.devex.com/funding",
        "priority": 4,
    },
    "unicef": {
        "name": "UNICEF",
        "url": "https://www.unicef.org/supply/procurement",
        "priority": 4,
    },
    "undp": {
        "name": "UNDP",
        "url": "https://procurement-notices.undp.org",
        "priority": 4,
    },
    "unesco": {
        "name": "UNESCO",
        "url": "https://en.unesco.org",
        "priority": 4,
    },
    "isdb": {
        "name": "Islamic Development Bank",
        "url": "https://www.isdb.org",
        "priority": 4,
    },
    "badea": {
        "name": "BADEA",
        "url": "https://www.badea.org",
        "priority": 4,
    },
}

SCRAPER_SETTINGS = {
    "timeout": 15,
    "max_retries": 3,
    "user_agents": [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    ],
}
